name: k8s Pipeline

on:
  push:
    branches:
      - main  # Or your desired deployment branch

jobs:
  build-and-deploy:
    permissions:
      contents: read # for actions/checkout to fetch code
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
    runs-on: ubuntu-latest
    env:
      AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
    
      - name: Deploy to AWS EKS
        run: |
          aws eks --region ${{ secrets.AWS_REGION }} update-kubeconfig --name ${{ secrets.CLUSTER_NAME }}
          kubectl apply -f frontend_deployment.yaml
          kubectl apply -f backend.yaml
          kubectl apply -f database.yaml   
          kubectl apply -f secret.yaml
          kubectl apply -f service.yaml